server:
  port: 10086

spring:
  application:
    name:

eureka:
  client:
    service-url:
      # eureka 服务地址, 如果是集群的话; 需要指定其它集群eureka地址
      defaultzone: http://127.0.0.1:10086/eureka
    #不注册自己
    register-with-eureka: false
    #不拉取服务
    fetch-registry: false
